# -*- coding: utf-8 -*-
"""dead_zone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18MSVyrNmRib_nuX8nWCNjiWPG69P_Um2

#This function has 3 parameters
1.a：the distance between front wheel and rear wheel

2.theta：the turning angle,default=20 degrees

3.target：a list consists of object's location[x, y]
#origin of coordinates is camera's location
#r is the gyroradius of rear wheel
#turn right, center of turning circle(r,-a)
#upper circle y： y_up = sqrt(r^2-(x-r)^2) - a
#y1 = y_up
"""

import math

def dead_zone(a, target, theta=20):
  x = target[0]
  y = target[1]
  theta_rad = math.radians(theta)
  r = a/math.tan(theta_rad)

  if theta==45:
    r = a/1

  #print(f'r={r}')

#   y_up = math.sqrt(math.pow(r,2) - math.pow((x-r),2)) - a
  y_up = abs((math.pow(r,2) - math.pow((x-r),2))**0.5) - a
  y1 = y_up

  #print(f'y1={y1}')

  distance = abs(y1-y)

  #print(f'distance={distance}')
  return distance
